import * as fs from "fs";
import type { AnalysisReport } from "../types";

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function complexityColor(c: number): string {
  if (c > 15) return "#f87171";
  if (c > 10) return "#facc15";
  return "#4ade80";
}

export function writeHtmlReport(report: AnalysisReport, outputPath: string): void {
  const topFunctions = [...report.functions]
    .sort((a, b) => b.complexity - a.complexity)
    .slice(0, 20);

  const functionsRows = topFunctions
    .map(
      (fn) =>
        `<tr>
          <td style="color:${complexityColor(fn.complexity)};font-weight:700">${fn.complexity}</td>
          <td>${escapeHtml(fn.name)}</td>
          <td class="dim">${escapeHtml(fn.file)}:${fn.line}</td>
          <td>${fn.lineCount}</td>
        </tr>`
    )
    .join("\n");

  const godFileRows = report.godFiles
    .map(
      (f) =>
        `<tr>
          <td>${escapeHtml(f.path)}</td>
          <td>${f.lines}</td>
          <td>${f.functions}</td>
        </tr>`
    )
    .join("\n");

  const circularRows = report.circularDeps
    .map(
      (d) =>
        `<tr><td>${d.cycle.map(escapeHtml).join(" → ")}</td></tr>`
    )
    .join("\n");

  const coupledRows = report.mostCoupled
    .map(
      (f) =>
        `<tr>
          <td>${escapeHtml(f.path)}</td>
          <td>${f.importedBy.length}</td>
        </tr>`
    )
    .join("\n");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Code Quality Report</title>
<style>
  :root { --bg: #0f172a; --surface: #1e293b; --text: #e2e8f0; --accent: #38bdf8; --green: #4ade80; --red: #f87171; --yellow: #facc15; --border: #334155; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: system-ui, -apple-system, sans-serif; background: var(--bg); color: var(--text); padding: 2rem; }
  h1 { color: var(--accent); margin-bottom: 0.5rem; }
  h2 { color: var(--accent); margin: 2rem 0 1rem; font-size: 1.2rem; }
  .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
  .card { background: var(--surface); border: 1px solid var(--border); border-radius: 12px; padding: 1.2rem; }
  .card .label { font-size: 0.85rem; color: #94a3b8; }
  .card .value { font-size: 1.6rem; font-weight: 700; margin-top: 0.3rem; }
  table { width: 100%; border-collapse: collapse; background: var(--surface); border-radius: 12px; overflow: hidden; margin-bottom: 1rem; }
  th { background: #334155; text-align: left; padding: 0.7rem 1rem; font-size: 0.8rem; color: #94a3b8; text-transform: uppercase; }
  td { padding: 0.6rem 1rem; border-top: 1px solid var(--border); }
  .dim { color: #94a3b8; }
  .ok { color: var(--green); }
  footer { margin-top: 3rem; text-align: center; color: #64748b; font-size: 0.8rem; }
</style>
</head>
<body>
<h1>Code Quality Report</h1>

<div class="grid">
  <div class="card"><div class="label">Files</div><div class="value">${report.scannedFiles}</div></div>
  <div class="card"><div class="label">Lines</div><div class="value">${report.totalLines.toLocaleString()}</div></div>
  <div class="card"><div class="label">Functions</div><div class="value">${report.functions.length}</div></div>
  <div class="card"><div class="label">God Files</div><div class="value" style="color:${report.godFiles.length > 0 ? "var(--yellow)" : "var(--green)"}">${report.godFiles.length}</div></div>
  <div class="card"><div class="label">Circular Deps</div><div class="value" style="color:${report.circularDeps.length > 0 ? "var(--red)" : "var(--green)"}">${report.circularDeps.length}</div></div>
</div>

<h2>Most Complex Functions</h2>
<table>
  <thead><tr><th>Complexity</th><th>Function</th><th>Location</th><th>Lines</th></tr></thead>
  <tbody>${functionsRows || '<tr><td colspan="4" class="ok">No functions found</td></tr>'}</tbody>
</table>

${
  report.godFiles.length > 0
    ? `<h2>God Files</h2>
<table>
  <thead><tr><th>File</th><th>Lines</th><th>Functions</th></tr></thead>
  <tbody>${godFileRows}</tbody>
</table>`
    : '<p class="ok">✅ No god files detected</p>'
}

${
  report.circularDeps.length > 0
    ? `<h2>Circular Dependencies</h2>
<table>
  <thead><tr><th>Cycle</th></tr></thead>
  <tbody>${circularRows}</tbody>
</table>`
    : '<p class="ok">✅ No circular dependencies</p>'
}

${
  report.mostCoupled.length > 0
    ? `<h2>Most Coupled Files</h2>
<table>
  <thead><tr><th>File</th><th>Imported By</th></tr></thead>
  <tbody>${coupledRows}</tbody>
</table>`
    : ""
}

<footer>Generated by code-quality-cli at ${report.timestamp}</footer>
</body>
</html>`;

  fs.writeFileSync(outputPath, html, "utf-8");
}
